Weather Story WFO Publish Confirmation
weather-gov/weather.gov pull request #1392
Opened 2024-06-26 20:54 UTC by eric-gade

## What does this PR do? 🛠️
After eons, this PR addresses #1269. The gist is that when creating a new Weather Story and entering a linked WFO, authors should see a dialog of some sort informing them that there is another Weather Story already published with the same WFO. The dialog will have options to save a draft, cancel, or "replace" -- meaning unpublish the other Weather Story first, then publish the new one.

## What does the reviewer need to know? 🤔
### Hey, isn't there a way to already do this? ###
![th](https://github.com/weather-gov/weather.gov/assets/105373963/4cee0e1c-5290-4e50-9d36-700a6dbc7277)
  
**No.**
  
I spent a significant amount of time trying to get this "confirmation, with original form data" concept to work via various Drupal APIs and patterns. None of them worked.
  
After _days_ of poking at it, I threw my hands up and decided to go with Javascript and some basic hook/template alterations.
  
### Ok, sure, but how does it work? ###
We add a custom [JS file](https://github.com/weather-gov/weather.gov/blob/eg-1269-basic-js-ws-confirmation/web/themes/weathergov_admin/assets/js/weather-story-modal.js) as a theme library called `weather-story-modal-dialog` which handles the logic of an otherwise inert `<dialog>` element that is now present in the template for adding weather stories.
  
In the admin theme file, we add a few helper methods and hooks that will load this library.
  
Additionally, if the form is a Weather Story create form, the hook will query the system for all weather stories that are currently published, passing information about all of them -- including and especially i[nformation about their linked WFO Terms](https://github.com/weather-gov/weather.gov/blob/eg-1269-basic-js-ws-confirmation/web/themes/weathergov_admin/weathergov_admin.theme#L196-L217) -- to the template file as [a JSON object tucked away in a script tag](https://github.com/weather-gov/weather.gov/blob/eg-1269-basic-js-ws-confirmation/web/themes/weathergov_admin/templates/page--node--add--weather-story.html.twig#L61-L63).
  
If the user decides to publish anyway, all existing published Weather Stories with the same WFO will be archived. This happens [by default in the publish action now](https://github.com/weather-gov/weather.gov/blob/eg-1269-basic-js-ws-confirmation/web/themes/weathergov_admin/weathergov_admin.theme#L109-L112), and is not unique to the dialog.
  
### Boring! How can I just try it out? ###
Here are some steps to follow to try it out locally:
* `zap` your containers
* Create a Weather Story for a specific WFO
* Publish the story
* Go back to the content page, and try to add a new Weather Story. Select the same WFO
* Click "Preview"
* Click the back link
* Click "Publish"
* A dialog should appear warning you about the original story being already published. Click "replace"
* You should see a message saying the new story was published and the old one was unpublished
* In the content list, there should only be one published weather story

## Screenshots (if appropriate): 📸
<details>
<summary>Visual summary of "replacing" with a new weather story for Nashville</summary>
  
![Screenshot 2024-06-26 at 4 23 21 PM](https://github.com/weather-gov/weather.gov/assets/105373963/fdc077ed-1277-49d7-ad38-f3e377247463)
![Screenshot 2024-06-26 at 4 23 53 PM](https://github.com/weather-gov/weather.gov/assets/105373963/224d763e-2fe7-46e5-9df9-f4e8c9787b15)
![Screenshot 2024-06-26 at 4 24 26 PM](https://github.com/weather-gov/weather.gov/assets/105373963/5dbcae63-db6f-46df-9e43-4eefab8ae32e)
![Screenshot 2024-06-26 at 4 24 36 PM](https://github.com/weather-gov/weather.gov/assets/105373963/61cf121e-d041-4925-8172-c21cf65bf119)
![Screenshot 2024-06-26 at 4 24 43 PM](https://github.com/weather-gov/weather.gov/assets/105373963/50041b03-2c69-43d9-8852-e3a5487a1ecc)

</details>

2024-06-27 00:20 UTC, greg-does-weather requested changes
This is quite good. I know it's not what you originally set out to do, but this is nice. One comment that I think needs fixed, but once that's done, I think this is ready to ship and celebrate.

2024-06-27 00:20 UTC, greg-does-weather commented on web/themes/weathergov_admin/assets/js/weather-story-modal.js
> +      const targetButton = document.getElementById(
This is ***clever***.

2024-06-28 12:59 UTC, eric-gade commented on web/themes/weathergov_admin/weathergov_admin.theme
> +    weathergov_unpublish_published_weather_stories($wfo_id);
Whoa, oof. Good catch

2024-06-28 13:20 UTC, eric-gade commented on web/themes/weathergov_admin/weathergov_admin.theme
> +    weathergov_unpublish_published_weather_stories($wfo_id);
Should be fixed now in https://github.com/weather-gov/weather.gov/pull/1392/commits/7cd1abaf56b281bdf5a4cca445f1553d19c15c0d thanks

2024-07-01 15:45 UTC, greg-does-weather approved these changes
Looks good

2024-07-02 14:29 UTC, merged