Add an app manifest
weather-gov/weather.gov pull request #1924
Opened 2024-10-15 20:06 UTC by greg-does-weather

## What does this PR do? 🛠️

By adding an app manifest, we get some control over what it looks like when a user "installs" weather.gov to their device. One big gotcha is that the manifest icons cannot have transparency, so as a first pass, I gave them a green background so we could see how they render on-device.

rough start for #1703

2024-10-15 20:25 UTC, jamestranovich-noaa requested changes
Are we addressing apple touch icons specifically in this PR? if so, don't we need a `rel="apple-touch-icon"` for some of these?

2024-10-15 21:17 UTC, greg-does-weather commented
No. iOS will use the icons defined in the app manifest. It only uses the `apple-touch-icons` if there is ***NOT*** a manifest.

2024-10-15 21:37 UTC, greg-does-weather commented
That's totally fair. I'll convert this to a WIP and we can revisit it later.

I _think_ for Android users, adding this manifest should cause the default browser to prompt users to install the app. For iOS users, it's more complicated because Apple hasn't seen fit to elevate web apps to first-class status yet (which is ironic, since that was the promise of iOS at the beginning, but 🤷‍♂️). But it should fix the icon issues anyway, and that's not nothing. 😛

2024-10-16 14:05 UTC, colinmurphy01 approved these changes

2024-10-23 16:02 UTC, jamestranovich-noaa approved these changes

2024-10-23 16:16 UTC, merged