Remove inline styles from the current conditions component
weather-gov/weather.gov pull request #313
Opened 2023-10-17 17:55 UTC by greg-does-weather

## What's wrong?

When it was originally created, the styles for the current conditions component were hardcoded right into the component code. Instead, it should use USWDS utility classes.

## How does this PR fix it? 

- Swaps out font size styles for USWDS utility classes
- Swaps out margins for utility classes
- Pulls the styling that's unique to the component into its own sass file

This component is probably going to need some more styling work in order to be *right*, but this is a step in the right direction.

![image](https://github.com/weather-gov/weather.gov/assets/142943695/f0b02b65-dcf1-42f5-a2e6-170ae9df7aeb)

Closes #198.

## Types of changes

- [x] 🐛 Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the code style of this project.

2023-10-17 22:24 UTC, claire-skies-noaa requested changes
This is great, Greg! Thanks for creating the component sass. Let's start using USWDS utility mixins instead of hardcoding values. I've included code suggestions. As long you add 
`@use "uswds-core" as *;` at the top of the SASS partial, you'll have access to all utility mixins and tokens. 

References:

[Height and width mixins](https://designsystem.digital.gov/utilities/height-and-width/#utility-mixins)
[The color tokens and mixins](https://designsystem.digital.gov/design-tokens/color/theme-tokens/#using-theme-color-tokens-2)

2023-10-17 22:24 UTC, claire-skies-noaa commented on web/themes/new_weather_theme/assets/sass/components/_current-conditions.scss
> +    height: 64px;
```suggestion
    @include u-height(8);
```

2023-10-17 22:24 UTC, claire-skies-noaa commented on web/themes/new_weather_theme/assets/sass/components/_current-conditions.scss
> +      height: 16px;
```suggestion
      @include u-height(2);
```

2023-10-17 22:24 UTC, claire-skies-noaa commented on web/themes/new_weather_theme/assets/sass/components/_current-conditions.scss
> +      width: 16px;
```suggestion
      @include u-height(2);
```

2023-10-17 22:24 UTC, claire-skies-noaa commented on web/themes/new_weather_theme/assets/sass/components/_current-conditions.scss
> +      fill: black;
```suggestion
      fill: color('black');
```

2023-10-18 22:09 UTC, greg-does-weather commented
@claire-skies-noaa Thank you! I'm going to have to get into the habit of keeping the USWDS reference open more often.

2023-10-19 15:22 UTC, merged